services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      timeout: 3s
  graphite:
    image: 'graphiteapp/graphite-statsd:latest'
    ports:
      - '81:80' # Web interface
      - '2003:2003'
      - '2004:2004'
      - '2023:2023'
      - '2024:2024'
      - '8125:8125/udp'
      - '8126:8126'
    volumes:
      - ./graphite_data:/opt/graphite/storage
      - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
    environment:
      - 'GRAPHITE_DBNAME=graphite'
      - 'GRAPHITE_USER=graphite'
      - 'GRAPHITE_PASSWORD=admin'
    depends_on:
      - postgres
    restart: always
